# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/varnish"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/redis"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/rabbitmq"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/xdebug3"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/node"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/magento2"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/magento2/xdebug3"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/magento2/blackfire"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/magento1"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/magento1/xdebug3"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/magento1/blackfire"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/blackfire"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/opensearch"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/nginx"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/mysql"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/mariadb"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/mailhog"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/magepack"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/elasticsearch"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/dnsmasq"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/images/php-fpm/dashboard"
    schedule:
      interval: "daily"
